package br.com.fchristiano.calcdeploymenttime.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "deployments_time")
public class DeploymentTime implements Serializable {

	private static final long serialVersionUID = 1l;

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@NotNull
	private String component;

	@NotNull
	private String action;

	@NotNull
	private String status;

	// Public methods
	public DeploymentTime() {
	}

	public DeploymentTime(long id) {
		this.id = id;
	}

	public DeploymentTime(String component, String action) {
		this.component = component;
		this.action = action;
	}

	public DeploymentTime(String component, String action, String status) {
		this.component = component;
		this.action = action;
		this.status = status;
	}

	// Getter and setter methods
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getComponent() {
		return component;
	}

	public void setComponent(String component) {
		this.component = component;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
